version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6380:6379'
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3.7.0-debian-10-r188'
    networks:
      emob:
        aliases:
          - zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2.8.1-debian-10-r31'
    networks:
      emob:
        aliases:
          - kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  emob:
    driver: bridge
